version: "3.8"

services:
  caddy:
    image: caddy:2
    restart: Unless-stopped
    ports:
      - "10.0.0.2:80:8080"
    env:
      HA_ACCESS_TOKEN: abcdefghijklmnopqrstuvwxyz0123456789
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  coredns:
    image: coredns/coredns
    restart: Unless-stopped
    ports:
      - "10.0.0.2:53:1053/udp"
    volumes:
      - ./Corefile:/dns/Corefile
    command: -dns.port=1053 -conf /dns/Corefile
